//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develandoo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    /// <summary>
    /// Database context, it let me to work with database via LINQ (Entities)
    /// </summary>
    public partial class DevelandooBaseEntities : DbContext
    {
        public DevelandooBaseEntities()
            : base("name=DevelandooBaseEntities")
        {
            //Create a database for application if it nor exists
            Database.SetInitializer(new CreateDatabaseIfNotExists<DevelandooBaseEntities>());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
          
          base.OnModelCreating(modelBuilder);
        }
    
        public virtual DbSet<Users> Users { get; set; }
    }
}
